[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
optimizer = true
optimizer_runs = 200
solc_version = "0.8.20"
via_ir = true
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[profile.default.fuzz]
runs = 256

[rpc_endpoints]
bscTestnet     = "${BSC_TESTNET_RPC_URL}"
opBNBTestnet   = "${OPBNB_TESTNET_RPC_URL}"
localhost      = "http://127.0.0.1:8545"

[etherscan]
bscTestnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api" }
